### PR TITLE
chore: fixed dark mode and added short bio

### LINKED ISSUE #625: Chore: UI Improvements
- [x] Make timer visible on Dark Mode
- [x] Add a short description to show in card previews
- [x] Dark mode improvements on the landing page

### PR DESCRIPTION
**Pull request by crisgarner**
# Description

Added short bio, provide some fixes to dark mode, removed markdown remover.

fix #625

## Confirmation

> [!IMPORTANT]
> We do not accept minor grammatical fixes (e.g., correcting typos, rewording sentences) unless they significantly improve clarity in technical documentation. These contributions, while appreciated, are not a priority for merging. If there is a grammatical error feel free to message the team.

- [x] I have read and understand MACI's [contributor guidelines](https://maci.pse.dev/docs/contributing) and [code of conduct](https://maci.pse.dev/docs/contributing/code-of-conduct).
- [x] I ran and verified that all tests pass according to MACI's [testing guide](https://maci.pse.dev/docs/guides/testing).

### CODE REVIEW

File: packages/interface/src/features/applications/components/ReviewApplicationDetails.tsx [hunk 1]
```diff
@@ -70,6 +70,8 @@ export const ReviewApplicationDetails = (): JSX.Element => {
 
         <ValueField required body={address} title="Created By" />
 
+        <ValueField required body={application.shortBio} title="Project description" />
```
Comment (kittybest) [inline packages/interface/src/features/applications/components/ReviewApplicationDetails.tsx:73]: Maybe rename the title as `Short Description`? Since it's same as the title of `application.bio`

**Review by kittybest — COMMENTED** [review]
Thanks! Just a question

**Comment by crisgarner** [comment]
Thanks! solved the conflicts

**Review by kittybest — APPROVED** [review]
thanks!
