### PR TITLE
fix: catch error for fetch subgraph

### LINKED ISSUE #526: bug(frontend): maci.tallies return error on the page
**Description**
image
There are several error api call in the console, sometimes even block the page.

### PR DESCRIPTION
**Pull request by kittybest**
**Description**

- [x] if there's an error for `fetchTally`, return empty array `[]`
- [x] check all the subgraph fetch function and wrap them with `catch` error or not causing any error

**Related Issues**
close #526

### CODE REVIEW

File: packages/interface/src/utils/fetchTally.ts [hunk 1]
```diff
@@ -48,7 +48,9 @@ export async function fetchTally(id: string): Promise<Tally | undefined> {
     body: JSON.stringify({
       query: tallyQuery.replace("id: $id", `id: "${id}"`),
     }),
-  }).then((response: GraphQLResponse) => response.data?.tally);
+  })
+    .then((response: GraphQLResponse) => response.data?.tally)
+    .catch(() => undefined);
```
Comment (ctrlc03) [inline packages/interface/src/utils/fetchTally.ts:53]: should this also return [] rather than undefined?

Comment (kittybest) [reply packages/interface/src/utils/fetchTally.ts:53]: this is just `fetchTally`, and this is actually not used, what you mentioned should be `fetchTallies`.
for `fetchTally` it accept `undefined` or `Tally`.
